[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy",
    "PyYAML",
    "pybind11",
    "pip",
    "cmake",
    "ninja"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp310-*"
build-verbosity = "3"
[tool.cibuildwheel.macos]
archs = ["arm64"]
environment = { LIB_ARCH = "arm64" }