PI_XFAIL_SET = {
    # view op
    "BernoulliFloatModule_basic",
    "ElementwiseFlattenBroadcastModule_basic",
    "FlattenDynamicModule_basic",
    "ElementwiseExpm1Module_basic",
    "FlattenRank0Module_basic",
    "UniformModule_basic",

    # torchvision
    "IouOfModule_basic",
    "ResNet18Module",
    "ResNet18Module_basic",
    "ResNet18StaticModule_basic",
    "MobilenetV3Module_basic",

    # tuple returns
    # torhc-mlir handles this incorrectly - if you tuple up the returns, it'll then unpack them during the
    # AdjustCallingConventionsPass but won't update the funcop type correctly (and thus the verifier throws
    # error: 'func.return' op has 2 operands, but enclosing function (@forward) returns 1)
    "AtenEmbeddingBagSumExample_basic",
    "Aten_EmbeddingBagExample_basic",
    "TestMultipleTensorAndPrimitiveTypesReturn_basic",
    "TestMultipleTensorReturn_basic",

    # python cast type return
    "BoolFloatConstantModule_basic",
    "BoolIntConstantModule_basic",
    "SqrtIntConstantModule_basic",

    # type/api overload
    "LogSoftmaxBackwardModule",
    "SoftmaxBackwardModule_basic",
    "LogSoftmaxBackwardModule_basic",
    "SortIntListReverse_basic", # just compares lists...
    "SortIntList_basic",
    "UniformNoCorrelationModule_basic",  # TypeError: 'torch_mlir._mlir_libs._mlir.ir.OpResult' object is not subscriptable

    # segfault during lowering to linalg (47)
    "CopyModule_basic",
    "CopyWithDifferentDTypesAndSizesModule_basic",
    "CopyWithDifferentDTypesModule_basic",
    "CopyWithDifferentSizesModule_basic",
    "EmptyLikeMemoryFormatModule_basic",
    "EmptyLikeModule_defaultDtype",
    "EmptyLikeModule_falsePinMemory",
    "EmptyLikeModule_float",
    "EmptyLikeModule_int",
    "EmptyModule_contiguous",
    "EmptyModule_defaultDtype",
    "EmptyModule_falsePinMemory",
    "EmptyModule_float",
    "EmptyModule_int",
    "Fill_TensorFloat32WithFloat32_basic",
    "Fill_TensorFloat32WithFloat64_basic",
    "Fill_TensorFloat32WithInt64_basic",
    "Fill_TensorFloat64WithFloat32_basic",
    "Fill_TensorFloat64WithFloat64_basic",
    "Fill_TensorFloat64WithInt64_basic",
    "IndexPut1DFloatNonAccumulateModule_basic",
    "IndexPutImpl1DFloatAccumulateModule_basic",
    "IndexPutImpl1DFloatNonAccumulateModule_basic",
    "IndexPutImpl1DIntAccumulateModule_basic",
    "IndexPutImpl1DIntNonAccumulateModule_basic",
    "IndexPutImpl2DFloatAccumulateModule_basic",
    "IndexPutImpl2DFloatNonAccumulateModule_basic",
    "IndexPutImpl2DIntAccumulateModule_basic",
    "IndexPutImpl2DIntNonAccumulateModule_basic",
    "IndexPutImpl3DFloatAccumulateModule_basic",
    "IndexPutImpl3DFloatNonAccumulateModule_basic",
    "IndexPutImpl3DIntAccumulateModule_basic",
    "IndexPutImpl3DIntNonAccumulateModule_basic",
    "MaxPool2dCeilModeTrueModule_basic",
    "MaxPool2dModule_basic",
    "NewEmptyModuleDefaultDtype_basic",
    "NewEmptyModuleDefaultDtype_basic",
    "NewEmptyModuleFalsePinMemory_basic",
    "NewEmptyModuleFloat2D_basic",
    "NewEmptyModuleFloat3D_basic",
    "NewEmptyModuleInt2D_basic",
    "NewEmptyModuleInt3D_basic",
    "NewEmptyModuleLayoutIntDtype_basic",
    "NewEmptyModuleNonDefaultFloatDtype_basic",
    "NewEmptyModuleNonDefaultIntDtype_basic",
    "NewEmptyStridedModuleDefaultDtype_basic",
    "ZeroFloat32Module_basic",
    "ZeroInt32Module_basic",
    "ZeroInt64Module_basic",

    # eager/lazy materialization (24)
    "AdaptiveAvgPool2dNonUnitOutputSizeDynamicModule_basic",
    "AdaptiveAvgPool2dNonUnitOutputSizeStaticModule_basic",
    "AdaptiveAvgPool2dUnitOutputSizeDynamicModule_basic",
    "AdaptiveAvgPool2dUnitOutputSizeStaticModule_basic",
    "BatchNorm1DModule_basic",
    "BatchNorm1DWith2DInputModule_basic",
    "BatchNorm2DModule_basic",
    "BatchNorm3DModule_basic",
    "EmbeddingModule1DIndices_basic",
    "EmbeddingModuleF16_basic",
    "EmbeddingModuleI32Static_basic",
    "EmbeddingModuleI32_basic",
    "EmbeddingModuleI64_basic",
    "HBC_basic",
    "HistogramBinningCalibrationByFeature",
    "LayerNormLastDimModule_basic",
    "LayerNormModule_basic",
    "LayerNormNormalizeOverAllDimsModule_basic",
    "TensorIntModule_basic",
    "TensorLiteralModule_basic",
    "TensorOpaqueLiteralModule_basic",
    "TensorToBoolZeroRank_basic",
    "TensorToBool_basic",
    "TorchPrimLoopForLikeModule_basic",
    "TorchPrimLoopWhileLikeModule_basic",

    # backends
    "ConvolutionBackwardModule2DPadded_basic",
    "ConvolutionBackwardModule2D_basic",

    # failed to legalize operation
    "NumpyTRank0Module_basic",
    "TModuleRank0_basic",
    "TModuleRank1_basic",
    "TModuleRank2_basic",

    # error: found an op that was marked as backend illegal
    "AtenToDeviceModule_basic",

    # int/float casts (29)
    "AtenIntBoolOpModule_basic",
    "AtenIntBoolOpConstFalseModule_basic",
    "AtenIntBoolOpConstTrueModule_basic",
    "AddIntModule_basic",
    "AtenIntTensorByteDtypeModule_basic",
    "AtenIntTensorCharDtypeModule_basic",
    "BoolFloatFalseModule_basic",
    "BoolFloatTrueModule_basic",
    "BoolIntFalseModule_basic",
    "BoolIntTrueModule_basic",
    "CeilFloatModule_basic",
    "DivFloatModule_basic",
    "DivIntModule_basic",
    "EqIntModule_basic",
    "GeFloatIntModule_basic",
    "GeFloatModule_basic",
    "GeIntModule_basic",
    "GtFloatIntModule_basic",
    "GtIntModule_basic",
    "MulIntModule_basic",
    "NeFloatIntModule_basic",
    "NeIntModule_basic",
    "ScalarImplicitFloatModule_basic",
    "ScalarImplicitIntModule_basic",
    "SqrtIntModule_basic",
    "SubFloatModule_basic",
    "SubIntModule_basic",
    "TensorToFloatZeroRank_basic",
    "TensorToFloat_basic",
    "TensorToIntZeroRank_basic",
    "TensorToInt_basic",
    "UnsafeViewCollapseDynamicWithAtenSizeIntModule_basic",
    "ViewCollapseDynamicWithAtenSizeIntModule_basic",
}
