name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:

  test-against-torch-mlir:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        arch: [ x86_64 ]
        python_version: [ "3.10" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install
        run: |
          pip install wheel cmake ninja
          pip install -r torch_mlir.requirements.txt
          pip install . -v --no-build-isolation

      - name: Test vs. torch-mlir ABI
        run: |
          python tests/unit/torch_mlir_ext_compatibility.py

      - name: Test vs. torch-mlir test-suite
        run: |
          PYTHONPATH=tests/torch_mlir python tests/torch_mlir/main.py
