name: Test

on:
  pull_request:
    branches:
      - main
      - nn_module
  push:
    branches:
      - main
      - nn_module
  workflow_dispatch:
    branches:
      - main
      - nn_module

jobs:

  test-against-torch-mlir:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        arch: [ x86_64 ]
        python_version: [ "3.10" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

#      - name: Install linux system packages
#        run: |
#          sudo apt-get update
#          sudo apt-get -y install ninja-build cmake clang

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install
        run: |
          pip install . \
            --pre torch-mlir torchvision \
            -f https://llvm.github.io/torch-mlir/package-index/ \
            --extra-index-url https://download.pytorch.org/whl/nightly/cpu \
            -v

      - name: Test vs. torch-mlir
        run: |
          PYTHONPATH=tests/torch_mlir python tests/torch_mlir/main.py
